language: php

services:
  - mysql

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - mysql -e 'CREATE DATABASE test__database;'


before_script:
  - composer install --no-progress --prefer-source

script:
  - vendor/bin/phpunit
