language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - composer install --no-progress --prefer-source

script:
  - phpunit
  - vendor/bin/phpcs ./inc/ --standard=phpcs.ruleset.xml --extensions=php
